{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3d1e58db-de1a-4970-8430-e172a15ca397",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-28 20:55:24.824 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:24.824 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.267 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run D:\\Miguel\\Anaconda_AIEP\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-11-28 20:55:25.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.267 Session state does not function when running a script without `streamlit run`\n",
      "2025-11-28 20:55:25.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.279 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.279 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.290 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.293 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.293 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.295 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.295 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.296 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.296 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.297 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.297 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.298 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.298 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.301 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.303 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.303 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.352 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2025-11-28 20:55:25.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:25.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:30.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:30.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-28 20:55:30.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import time\n",
    "from datetime import datetime\n",
    "\n",
    "# --- CONFIGURACIÓN DE LA PÁGINA ---\n",
    "st.set_page_config(\n",
    "    page_title=\"ConTech Pro\",\n",
    "    page_icon=\"👷‍♂️\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# --- ESTILOS CSS PERSONALIZADOS (Simulando Tailwind/Sass) ---\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "    .stMetric {\n",
    "        background-color: #f8fafc;\n",
    "        border: 1px solid #e2e8f0;\n",
    "        padding: 15px;\n",
    "        border-radius: 10px;\n",
    "    }\n",
    "    .stAlert {\n",
    "        padding: 10px;\n",
    "        border-radius: 8px;\n",
    "    }\n",
    "    div[data-testid=\"stSidebarNav\"] {\n",
    "        padding-top: 20px;\n",
    "    }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# --- DATOS MOCK (Simulación de Backend) ---\n",
    "ROLES = {\n",
    "    \"ADMIN\": \"Jefe de Obra / Admin\",\n",
    "    \"WORKER\": \"Trabajador / Operario\",\n",
    "    \"CLIENT\": \"Cliente / Inmobiliaria\"\n",
    "}\n",
    "\n",
    "if 'messages' not in st.session_state:\n",
    "    st.session_state.messages = [\n",
    "        {\"role\": \"assistant\", \"content\": \"Hola Carlos, ¿subiste los planos revisados de la Torre B?\"},\n",
    "        {\"role\": \"user\", \"content\": \"Sí, están en la carpeta 'Ingeniería/Versión Final'.\"}\n",
    "    ]\n",
    "\n",
    "# --- FUNCIONES DE VISTAS ---\n",
    "\n",
    "def render_kpis():\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    col1.metric(\"Presupuesto Ejecutado\", \"45%\", \"+2.5%\")\n",
    "    col2.metric(\"Días Sin Accidentes\", \"128\", \"Meta: 365\")\n",
    "    col3.metric(\"RFI Pendientes\", \"12\", \"-3 Criticos\", delta_color=\"inverse\")\n",
    "    col4.metric(\"Asistencia Hoy\", \"92%\", \"-1% vs ayer\")\n",
    "\n",
    "def view_dashboard_admin():\n",
    "    st.title(\"📊 Dashboard General\")\n",
    "    render_kpis()\n",
    "    \n",
    "    st.markdown(\"### 🏗️ Estado de Proyectos\")\n",
    "    projects_df = pd.DataFrame({\n",
    "        \"Proyecto\": [\"Edificio Altos del Parque\", \"Puente Bicentenario\", \"Mall Plaza Oeste\"],\n",
    "        \"Responsable\": [\"Ana L.\", \"Roberto G.\", \"Carlos M.\"],\n",
    "        \"Avance\": [65, 32, 88],\n",
    "        \"Estado\": [\"En Curso\", \"Retrasado\", \"Finalizando\"]\n",
    "    })\n",
    "    \n",
    "    # Formato condicional simple\n",
    "    st.dataframe(\n",
    "        projects_df,\n",
    "        column_config={\n",
    "            \"Avance\": st.column_config.ProgressColumn(\"Avance (%)\", format=\"%d%%\", min_value=0, max_value=100),\n",
    "            \"Estado\": st.column_config.TextColumn(\"Estado\")\n",
    "        },\n",
    "        use_container_width=True,\n",
    "        hide_index=True\n",
    "    )\n",
    "\n",
    "    col_noticias, col_grafico = st.columns([1, 2])\n",
    "    \n",
    "    with col_noticias:\n",
    "        st.subheader(\"🔔 Notificaciones\")\n",
    "        st.info(\"**Nueva normativa EPP:** Obligatorio uso de casco azul para supervisores.\")\n",
    "        st.warning(\"**Visita Técnica:** Mañana 10:00 AM - Inspectores Municipales.\")\n",
    "    \n",
    "    with col_grafico:\n",
    "        st.subheader(\"📈 Curva de Avance\")\n",
    "        chart_data = pd.DataFrame({\n",
    "            \"Semana\": [\"Sem 1\", \"Sem 2\", \"Sem 3\", \"Sem 4\"],\n",
    "            \"Programado\": [10, 25, 40, 60],\n",
    "            \"Real\": [10, 22, 35, 45]\n",
    "        })\n",
    "        st.line_chart(chart_data.set_index(\"Semana\"))\n",
    "\n",
    "def view_worker():\n",
    "    st.title(\"👷 Portal del Trabajador\")\n",
    "    \n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        if st.button(\"📍 MARCAR ENTRADA (GPS)\", type=\"primary\", use_container_width=True):\n",
    "            with st.spinner(\"Localizando...\"):\n",
    "                time.sleep(1)\n",
    "            st.success(\"✅ Entrada registrada a las 08:00 AM\")\n",
    "            \n",
    "    with col2:\n",
    "        if st.button(\"⚠️ REPORTAR INCIDENTE\", type=\"secondary\", use_container_width=True):\n",
    "            st.error(\"Formulario de incidente abierto\")\n",
    "\n",
    "    st.markdown(\"### 📋 Mis Tareas de Hoy\")\n",
    "    tasks = pd.DataFrame({\n",
    "        \"Tarea\": [\"Hormigonado Losa Piso 4\", \"Limpieza Zona Descarga\", \"Charla de Seguridad\"],\n",
    "        \"Horario\": [\"08:30 - 13:00\", \"14:00 - 16:00\", \"17:30 - 18:00\"],\n",
    "        \"Estado\": [\"En Progreso\", \"Pendiente\", \"Pendiente\"]\n",
    "    })\n",
    "    st.table(tasks)\n",
    "\n",
    "    st.info(\"💰 **Aviso:** El bono de producción se pagará este viernes 30.\")\n",
    "\n",
    "def view_client():\n",
    "    st.title(\"🏢 Portal del Cliente\")\n",
    "    st.markdown(\"### Resumen Ejecutivo: Edificio Altos del Parque\")\n",
    "    \n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        st.progress(65, text=\"Avance Físico: 65%\")\n",
    "        st.progress(58, text=\"Avance Financiero: 58%\")\n",
    "    \n",
    "    st.divider()\n",
    "    \n",
    "    tabs = st.tabs([\"📸 Galería de Avance\", \"📝 Requisitos y Cambios\"])\n",
    "    \n",
    "    with tabs[0]:\n",
    "        st.markdown(\"Vista aérea del proyecto\")\n",
    "        # Placeholder de imagen (usando un cuadro gris o imagen real si tuvieras)\n",
    "        st.image(\"https://via.placeholder.com/800x400?text=Foto+Drone+Semana+42\", use_column_width=True)\n",
    "        \n",
    "    with tabs[1]:\n",
    "        st.markdown(\"#### Solicitudes de Cambio\")\n",
    "        reqs = pd.DataFrame({\n",
    "            \"Requisito\": [\"Cambio Terminaciones Hall\", \"Ampliación Estacionamiento\"],\n",
    "            \"Prioridad\": [\"Alta\", \"Media\"],\n",
    "            \"Costo\": [\"+$1.2M\", \"TBD\"],\n",
    "            \"Estado\": [\"Aprobado\", \"En Evaluación\"]\n",
    "        })\n",
    "        st.dataframe(reqs, use_container_width=True)\n",
    "\n",
    "def view_chat():\n",
    "    st.title(\"💬 Chat Interno de Obra\")\n",
    "    \n",
    "    # Mostrar historial\n",
    "    for message in st.session_state.messages:\n",
    "        with st.chat_message(message[\"role\"]):\n",
    "            st.markdown(message[\"content\"])\n",
    "\n",
    "    # Input de usuario\n",
    "    if prompt := st.chat_input(\"Escribe un mensaje al equipo...\"):\n",
    "        st.session_state.messages.append({\"role\": \"user\", \"content\": prompt})\n",
    "        with st.chat_message(\"user\"):\n",
    "            st.markdown(prompt)\n",
    "        \n",
    "        # Respuesta simualda\n",
    "        time.sleep(1)\n",
    "        response = \"Recibido. Lo revisaré en la reunión de coordinación.\"\n",
    "        st.session_state.messages.append({\"role\": \"assistant\", \"content\": response})\n",
    "        with st.chat_message(\"assistant\"):\n",
    "            st.markdown(response)\n",
    "\n",
    "# --- SIDEBAR & NAVEGACIÓN ---\n",
    "\n",
    "with st.sidebar:\n",
    "    st.header(\"🏗️ CONTECH PRO\")\n",
    "    \n",
    "    # Selector de Rol (Simulación de Login)\n",
    "    selected_role = st.selectbox(\n",
    "        \"Simular Rol:\",\n",
    "        options=list(ROLES.keys()),\n",
    "        format_func=lambda x: ROLES[x]\n",
    "    )\n",
    "    \n",
    "    st.divider()\n",
    "    \n",
    "    # Menú dinámico según rol\n",
    "    menu_options = []\n",
    "    if selected_role == \"ADMIN\":\n",
    "        menu_options = [\"Dashboard\", \"Documentos\", \"Personal\", \"Calidad\", \"Chat\"]\n",
    "    elif selected_role == \"WORKER\":\n",
    "        menu_options = [\"Mi Jornada\"]\n",
    "    elif selected_role == \"CLIENT\":\n",
    "        menu_options = [\"Avance General\"]\n",
    "        \n",
    "    selected_page = st.radio(\"Navegación\", menu_options)\n",
    "    \n",
    "    st.divider()\n",
    "    st.caption(f\"Usuario: {ROLES[selected_role]}\")\n",
    "    st.caption(\"🟢 En línea\")\n",
    "\n",
    "# --- CONTROLADOR PRINCIPAL ---\n",
    "\n",
    "if selected_role == \"ADMIN\":\n",
    "    if selected_page == \"Dashboard\":\n",
    "        view_dashboard_admin()\n",
    "    elif selected_page == \"Chat\":\n",
    "        view_chat()\n",
    "    else:\n",
    "        st.info(f\"Módulo de {selected_page} en desarrollo\")\n",
    "        \n",
    "elif selected_role == \"WORKER\":\n",
    "    view_worker()\n",
    "    \n",
    "elif selected_role == \"CLIENT\":\n",
    "    view_client()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff0339c2-c1ce-43f1-9be8-3be3bc820784",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
